# The version of docker compose to use
version: '3.4'

volumes:
    easyenv_opt:
        external:
            name: easyenv_opt
    easyenv_ssh:
        external:
            name: easyenv_ssh

x-easyenv-common:
    common:
        &easyenv-common
        image: robdmc/easyenv:latest
        privileged: true
        volumes:
           - easyenv_opt:/opt:delegated
           - easyenv_ssh:/root/.ssh:delegated
           - ./container_files/vim:/root/.vim:delegated
           - ~:/host:delegated
           - .:/docker:delegated
           ##################################################################
           # Replace this with
           # projects/path/on/your/computer:/root/projects
           - ~/rob/repos:/root/projects
           ##################################################################
services:
    shell:
        <<: *easyenv-common
        command: /bin/bash
        ports:
            - "5555:5555"
            - "8000:8000"
            - "8888:8888"


    notebook:
        <<: *easyenv-common
        command: bash -c 'source ~/.bashrc && jupyter notebook --allow-root --ip 0.0.0.0 --port 9999 --NotebookApp.iopub_data_rate_limit=10000000000'
        ports:
            - "9999:9999"
